from astropy.io import fits
import numpy as np
import shutil
import os

def make_maps(gal_file):
    """
    Generates segmentation maps for a galaxy FITS file using Source Extractor.

    This function runs Source Extractor twice on the input galaxy FITS file, using two different
    configurations ('cold' and 'hot' detection thresholds) to produce two separate segmentation
    maps. These maps identify the sources detected in the image under different sensitivity
    settings, which are later combined to create a comprehensive mask.

    Args:
        gal_file (str): The file path to the galaxy's FITS image.
    """
    comando_cold = f'source-extractor {gal_file} -c ./wraith/configCold.sex'
    os.system(comando_cold)

    comando_hot = f'source-extractor {gal_file} -c ./wraith/configHot.sex'
    os.system(comando_hot)

def combine_maps():
    """
    Combines the 'cold' and 'hot' segmentation maps into a single FITS file.

    This function reads the two segmentation maps generated by `make_maps` ('cold.fits' and 'hot.fits').
    It then combines them into a single map where the detected sources from both maps are preserved
    but assigned unique integer labels. The 'hot' map's labels are offset to avoid collision with
    the 'cold' map's labels. The resulting combined map is saved to 'combined_map.fits', and the
    original 'cold' and 'hot' maps are deleted.
    """
    cold_map = 'cold.fits'
    hot_map = 'hot.fits'

    with fits.open(cold_map) as hdul1, fits.open(hot_map) as hdul2:
        data1 = hdul1[1].data
        data2 = hdul2[1].data
        
        max_value = data1.max()
        
        data2_offset = np.where(data2 != 0, data2 + max_value + 1, 0)
        
        combined_data = np.where(data1 != 0, data1, data2_offset)
        
        header1 = hdul1[1].header
        primary_header = hdul1[0].header
    
    new_hdu = fits.ImageHDU(data=combined_data, header=header1)
    primary_hdu = fits.PrimaryHDU(header=primary_header)
    
    combined_hdul = fits.HDUList([primary_hdu, new_hdu])
    combined_hdul.writeto('combined_map.fits', overwrite=True)
    os.remove(cold_map), os.remove(hot_map)

def remove_central_object():
    """
    Removes the central object from the combined segmentation map.

    This function identifies the object at the center of the 'combined_map.fits' file, which is
    assumed to be the main galaxy of interest, and removes it from the segmentation map. This is
    done by setting all pixels corresponding to the central object's label to zero. The resulting
    map, which contains only the surrounding sources, is saved as 'modified_map.fits'. The input
    'combined_map.fits' is then deleted.
    """
    comb_map = 'combined_map.fits'

    with fits.open(comb_map) as hdul:
        data = hdul[1].data
        
        center_y, center_x = data.shape[0] // 2, data.shape[1] // 2
        central_value = data[center_y, center_x]
        
        modified_data = np.where(data == central_value, 0, data)
        
        header = hdul[1].header
        primary_header = hdul[0].header
    
    new_hdu = fits.ImageHDU(data=modified_data, header=header)
    primary_hdu = fits.PrimaryHDU(header=primary_header)
    
    combined_hdul = fits.HDUList([primary_hdu, new_hdu])
    combined_hdul.writeto('modified_map.fits', overwrite=True)
    os.remove(comb_map)

def apply_mask(name, gal_name, gal_file):
    """
    Applies the final generated mask to the galaxy image.

    This function creates a final mask by combining a signal-to-noise ratio map with the
    segmentation map of surrounding objects ('modified_map.fits'). Pixels with a signal-to-noise
    ratio below a certain threshold are flagged, as are pixels belonging to detected surrounding
    sources. The resulting mask is saved as a new FITS file and moved to the appropriate
    directory for use in the IMFIT analysis.

    Args:
        name (str): The general identifier for the run or sample, used for directory naming.
        gal_name (str): The base name of the galaxy's FITS file.
        gal_file (str): The file path to the galaxy's FITS image.
    """
    actual_folder = os.getcwd()
    map_file = 'modified_map.fits'
    mask_file = os.path.splitext(gal_name)[0]
    mask_name = f'{mask_file}mask.fits'
    mask_dir = f'./{name}/mask'
    if not os.path.exists(mask_dir):
        os.mkdir(mask_dir)

    with fits.open(gal_file) as hdugal, fits.open(map_file) as hdumap:
        datasinal = hdugal[1].data
        dataruido = hdugal[3].data
        datamap = hdumap[1].data

        sr = datasinal / dataruido

        sr[np.where(sr < 3)] = 1
        sr[np.where(sr >= 3)] = 0

        mask = sr + datamap

        hdu_mask = fits.ImageHDU(data=mask)
        hdumap[1] = hdu_mask
        hdumap.writeto(mask_name, overwrite=True)
        os.remove(map_file)
        origin = os.path.join(actual_folder, mask_name)
        destiny = os.path.join(mask_dir, mask_name)
        shutil.move(origin, destiny)

